# SwiftLint Configuration for NFC Demo App

# Paths to include/exclude
included:
  - NFCDemo

excluded:
  - Carthage
  - Pods
  - DerivedData
  - .build
  - NFCDemoTests
  - NFCDemoUITests

# Disabled rules
disabled_rules:
  - trailing_whitespace
  - todo  # Allow TODO comments during development
  - line_length  # We set our own limit below

# Opt-in rules (not enabled by default)
opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - contains_over_first_not_nil
  - empty_count
  - empty_string
  - explicit_init
  - extension_access_modifier
  - fallthrough
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicit_return
  - joined_default_parameter
  - last_where
  - literal_expression_end_indentation
  - modifier_order
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - private_action
  - private_outlet
  - prohibited_super_call
  - redundant_nil_coalescing
  - redundant_type_annotation
  - sorted_first_last
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - unused_import
  - vertical_parameter_alignment_on_call
  - yoda_condition

# Rule configurations
line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 500
  error: 1000
  ignore_comment_only_lines: true

function_body_length:
  warning: 50
  error: 100

function_parameter_count:
  warning: 5
  error: 8

type_body_length:
  warning: 300
  error: 500

type_name:
  min_length: 3
  max_length:
    warning: 40
    error: 50
  excluded:
    - T
    - U
    - V

identifier_name:
  min_length:
    warning: 2
    error: 1
  max_length:
    warning: 40
    error: 50
  excluded:
    - id
    - URL
    - url
    - db
    - nfc
    - GPS
    - API

cyclomatic_complexity:
  warning: 10
  error: 20
  ignores_case_statements: true

nesting:
  type_level:
    warning: 2
    error: 3
  statement_level:
    warning: 5
    error: 10

# Custom rules
custom_rules:
  # Discourage force unwrapping
  no_force_unwrap:
    name: "Force Unwrapping"
    regex: '(\w+)!'
    match_kinds: identifier
    message: "Avoid force unwrapping - use guard let or if let instead"
    severity: warning

  # Encourage proper documentation
  documentation_required:
    name: "Documentation Required"
    regex: '(class|struct|enum|protocol) \w+[^{]*\{(?!.*\/\/\/)'
    message: "Public types should have documentation"
    severity: warning

  # Discourage print statements
  no_print_statements:
    name: "No Print Statements"
    regex: '\bprint\('
    message: "Use AppLogger instead of print statements"
    severity: warning

  # Encourage TODO format
  todo_format:
    name: "TODO Format"
    regex: '\/\/\s*TODO(?!:)'
    message: "TODO should be followed by a colon and description"
    severity: warning

# Analyzer rules
analyzer_rules:
  - unused_declaration
  - unused_import

# Reporter
reporter: "xcode" # Xcode-compatible output format

# Warnings
warning_threshold: 50
